"""Build an H2 Hamiltonian with qiskit-nature and serialize it to JSON.

Strictly speaking, UCCSD is an ansatz, not a Hamiltonian. In VQE workflows, one usually pairs a
UCCSD ansatz with a molecular electronic Hamiltonian generated by qiskit-nature. This example
shows both pieces:

1. Generate the H2 electronic Hamiltonian with ``PySCFDriver``.
2. Map the fermionic Hamiltonian to qubits with ``JordanWignerMapper``.
3. Wrap the qubit Hamiltonian in Qiskit's ``PauliEvolutionGate``.
4. Build the matching ``HartreeFock`` + ``UCCSD`` ansatz from the same problem metadata.
5. Serialize Pauli strings and real coefficients into a JSON file.

Requirements:
    pip install qiskit-nature pyscf
"""

from __future__ import annotations

import json
from pathlib import Path

from qiskit import QuantumCircuit
from qiskit.circuit.library import PauliEvolutionGate
from qiskit.quantum_info import SparsePauliOp
from qiskit_nature.second_q.circuit.library import HartreeFock, UCCSD
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.mappers import JordanWignerMapper
from qiskit_nature.units import DistanceUnit


def dump_qubit_hamiltonian_json(
    qubit_hamiltonian: SparsePauliOp,
    output_path: str | Path,
) -> None:
    coeffs = []
    for coeff in qubit_hamiltonian.coeffs:
        if abs(coeff.imag) > 1e-10:
            raise ValueError(f"Expected a real-valued qubit Hamiltonian, got coefficient {coeff!r}.")
        coeffs.append(float(coeff.real))

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(
            {
                "num_qubits": qubit_hamiltonian.num_qubits,
                "paulis": qubit_hamiltonian.paulis.to_labels(),
                "coeffs": coeffs,
            },
            f,
            indent=2,
        )


def main() -> None:
    driver = PySCFDriver(
        atom="H 0.0 0.0 0.0; H 0.0 0.0 0.735",
        basis="sto3g",
        charge=0,
        spin=0,
        unit=DistanceUnit.ANGSTROM,
    )
    problem = driver.run()

    fermionic_hamiltonian = problem.hamiltonian.second_q_op()
    mapper = JordanWignerMapper()
    qubit_hamiltonian = mapper.map(fermionic_hamiltonian)

    evolution_time = 0.25
    evolution_gate = PauliEvolutionGate(qubit_hamiltonian, time=evolution_time)

    evolution_circuit = QuantumCircuit(qubit_hamiltonian.num_qubits, name="H2 evolution")
    evolution_circuit.append(evolution_gate, range(qubit_hamiltonian.num_qubits))

    hartree_fock = HartreeFock(problem.num_spatial_orbitals, problem.num_particles, mapper)
    uccsd = UCCSD(
        problem.num_spatial_orbitals,
        problem.num_particles,
        mapper,
        initial_state=hartree_fock,
    )

    assert evolution_gate.num_qubits == qubit_hamiltonian.num_qubits
    assert uccsd.num_qubits == qubit_hamiltonian.num_qubits

    print("Molecule: H2 @ 0.735 A, basis=STO-3G")
    print(f"Number of spatial orbitals: {problem.num_spatial_orbitals}")
    print(f"Number of particles: {problem.num_particles}")
    print(f"Qubit Hamiltonian qubits: {qubit_hamiltonian.num_qubits}")
    print()
    print("Qubit Hamiltonian (SparsePauliOp):")
    print(qubit_hamiltonian)
    print()
    print(f"PauliEvolutionGate time: {evolution_time}")
    print("PauliEvolutionGate circuit:")
    print(evolution_circuit)
    print()
    print(f"UCCSD ansatz qubits: {uccsd.num_qubits}")
    print(f"UCCSD parameter count: {uccsd.num_parameters}")

    output_path = Path(__file__).resolve().parent / "hams" / "H2_frz_JW_sto3g.json"
    dump_qubit_hamiltonian_json(qubit_hamiltonian, output_path)
    print(f"Hamiltonian JSON written to: {output_path}")


if __name__ == "__main__":
    main()
